config/routes.rb
Rails.application.routes.draw do

  get 'games/index', to: 'games#index', as: 'games'
  get 'games/:id/', to: 'games#show', as: 'game'
  get 'games/:id/update', to: 'games#update'
  patch '/games/:id/update', to: 'games#update', as: 'game_update'

  get "/seasons", to: "seasons#index", as: "season"

  post "/seasons", to: "seasons#create"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  get "/players", to: "players#index", as: "players"
  get "/players/:id", to: "players#show", as: "player"
  

  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to: "users#show", as: "user"
  
  get "/picks/new", to: "picks#new", as: "new_pick"

  post "/users", to: "users#create"
  post "/picks", to: "picks#create"

  delete "/logout", to: "sessions#destroy"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/season.rb
class Season < ApplicationRecord
    after_create :schedule
    has_many :users
    has_many :teams, through: :users
    has_many :picks, through: :users 
    has_many :players, through: :picks
    has_many :games
    validates :team_id, uniqueness: true 

    def schedule
        @users = User.all.reject{|user| user.username == "admin" || user.season != Season.last}
        @users.each do |home|
          opponents_array = @users - [home]
          opponents_array.each do |opponent|
            t1 = Time.parse("2019-10-03")
            t2 = Time.parse("2020-04-04")
            s = rand(t1..t2).to_s
            Game.create(home: home, away: opponent, date: s, season: Season.last)
          end
        end
    end

    def schedule_create
        if self.games.length == 0 
          self.schedule 
        end
    end

    def draft(first_player_picks = [0, 7, 8, 15, 16, 23, 24, 31, 32, 39, 40, 47], second_player_picks = [1, 6, 9, 14, 17, 22, 25, 30, 33, 38, 41, 46], third_player_picks = [2, 5, 10, 13, 18, 21, 26, 29, 34, 37, 42, 45], fourth_player_picks = [3, 4, 11, 12, 19, 20, 27, 28, 35, 36, 43, 44], last_pick = [48])

        first_player = self.users[1]
        second_player = self.users[2]
        third_player = self.users[3]
        fourth_player = self.users[4]

        if first_player_picks.include?(self.picks.length)
            first_player
        elsif second_player_picks.include?(self.picks.length)
            second_player
        elsif third_player_picks.include?(self.picks.length)
            third_player
        elsif fourth_player_picks.include?(self.picks.length)
            fourth_player  
        else 
            first_player
        end
    end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def new
    @season = Season.new
  end

  def create 
    @season = Season.create(season_params)
    redirect_to seasons_path
  end

  def show
    @season = Season.find(params[:id])

  end

  def index
    @season = Season.last
    @users = User.all[1..4]   
    @sorted_users = @users.sort_by{|user| [-user.games_won(user.username), user.games_lost(user.username)]} 
  end

  private 
  def season_params 
    params.require(:season).permit(:number)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/create.html.erb
<h1>Seasons#create</h1>
<p>Find me in app/views/seasons/create.html.erb</p>

app/views/seasons/destroy.html.erb
<h1>Seasons#destroy</h1>
<p>Find me in app/views/seasons/destroy.html.erb</p>

app/views/seasons/index.html.erb
<div id="stansche" align="center"><h2><%= "Schedule and Standings of Season #{@season.number}"%></h2>
  <%if @season.picks.length == 48%> 
    <%@season.schedule_create%>
  <%end%>
<div id="standings"><table align="center">                         
    <tr>                          
      <th><%= "Team"%></th>
      <th><%= "Wins"%></th>
      <th><%= "Losses"%> 
    </tr>
<%@sorted_users.each do |user|%>     
    <tr>
        <td><%= link_to "#{user.team.hometown} #{user.team.name}", user_path(user.id) %></td>
        <td><%= user.games_won(user.username) %></td>   
        <td><%= user.games_lost(user.username) %></td>
    </tr>
  <% end %>                        
  </table></div>  

<div id="schedule"><table align="center">                         
        <tr>                          
          <th>Date</th>
          <th>Home Team</th>
          <th>Away Team</th>
          <th>Winning Team</th>
          <th>Losing Team</th>
        </tr>
    <%@season.games.sort_by{|games| games.date}.each do |game|%>     
        <tr>
            <td><%= link_to game.date[0..10], game_path(game.id) %></td>
            <td><%= link_to "#{game.home.team.hometown} #{game.home.team.name}", user_path(game.home.id) %></td>   
            <td><%= link_to "#{game.away.team.hometown} #{game.away.team.name}", user_path(game.away.id) %></td> 
            <% if game.winner %>
              <% winning_user = User.find_by username: game.winner %>
              <% winning_team = winning_user.team.name %>
              <% losing_user = User.find_by username: game.loser %>
              <% losing_team = losing_user.team.name%>
              <td><%= winning_team %> </td>
              <td><%= losing_team %> </td>
            <% end %>
        </tr>
      <% end %>                        
      </table></div>
    </div>
      

    

app/views/seasons/new.html.erb
<div class="form">
<%= form_tag "/seasons" do |f| %>
<%= f.label :number%>
<%= f.number_field :number%>

<%= f.submit "Create" %>
<% end %>
</div>

app/views/seasons/show.html.erb
<h1>Seasons#show</h1>
<p>Find me in app/views/seasons/show.html.erb</p>