config/routes.rb
Rails.application.routes.draw do

  get 'games/index', to: 'games#index', as: 'games'
  get 'games/:id/', to: 'games#show', as: 'game'
  get 'games/:id/update', to: 'games#update'
  patch '/games/:id/update', to: 'games#update', as: 'game_update'

  get "/seasons", to: "seasons#index", as: "season"

  post "/seasons", to: "seasons#create"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  get "/players", to: "players#index", as: "players"
  get "/players/:id", to: "players#show", as: "player"
  

  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to: "users#show", as: "user"
  
  get "/picks/new", to: "picks#new", as: "new_pick"

  post "/users", to: "users#create"
  post "/picks", to: "picks#create"

  delete "/logout", to: "sessions#destroy"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotseatHockey94</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/nes.css@latest/css/nes.min.css" rel="stylesheet" />
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar">
        <%if current_user%>
        <%= link_to 'Schedule', seasons_path, class: "nes-btn"%>
        <%= link_to 'Draft Page', players_path, class: "nes-btn is-primary"%>
        <%= link_to 'Make Selection', users_path(current_user.id), class: "nes-btn is-success"%>
        <%= link_to 'Team Roster', user_path(current_user.id), class: "nes-btn is-warning"%>
        <%= link_to 'Logout', {:controller=> "sessions", :action=> "destroy"}, :method => :delete, class: "nes-btn is-error"%>

        <%= submit_tag "#{current_user.username} is logged in.", class: "nes-btn is-disabled"%>

        <%else%>
        <h2><%= link_to "Login Required", login_path%></h2>
        <%end%>
    </div>
    <%= yield %>
  </body>
</html>